### PR TITLE
Add support to Rails 7.1, bump to v0.5.3

### PR DESCRIPTION
**Pull request by sanzstez**
Hello, I did changes like update to rails 7.0 from previous commits. Can you please check and merge it?

### CODE REVIEW

**Comment by rahulbir** [comment]
@glebm is there a way to update https://rubygems.org/gems/order_query to latest version?

**Comment by rahulbir** [comment]
@glebm pinging again in case this got missed.

**Comment by glebm** [comment]
Ah yeah it fell through the cracks. I will look into releasing an update sometime this week

**Comment by glebm** [comment]
Released 0.5.3!

**Pull request merged**
